package com.example.agent.evidence;

/**
 * An executable evidence entry (citation) — one item of the EVIDENCE INDEX.
 * <p>
 * Pairs an index number with the real query recorded by the backend and a
 * clickable deep-link URL. The LLM output may only reference {@code [E{n}]};
 * the query and URL are always resolved by the backend. If the model cites an
 * index that does not exist, the citation resolves to {@code resolved=false}
 * with no query or URL — fabricated evidence is impossible.
 */
public record Evidence(
        int index,
        String source,   // PROMETHEUS / LOKI / RUNBOOK
        String query,    // real query recorded by the backend (never generated by the LLM)
        String summary,  // one-line result summary
        String window,   // window description
        String url       // clickable deep link (e.g. Grafana explore); null for RUNBOOK
) {
    public static Evidence of(int index, String source, String query, String summary,
                              String window, String url) {
        return new Evidence(index, source, query, summary, window, url);
    }
}
